---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

.Docker solr-cluster-master:
  stage: deployment test
  script:
    - molecule test -s docker-solr-master
  tags:
    - aws

.Docker solr-cluster-slave:
  stage: deployment test
  script:
    - molecule test -s docker-solr-slave
  tags:
    - aws

.AWS solr-cluster-master:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-solr-master
  tags:
    - aws

.AWS solr-cluster-slave:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-solr-slave
  tags:
    - aws

AWS Windows solr-cluster-master:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-solr-master
  tags:
    - aws

AWS Windows solr-cluster-slave:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-solr-slave
  tags:
    - aws

.EPC solr-cluster-master:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-solr-master
  tags:
    - delegated

.EPC solr-cluster-slave:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-solr-slave
  tags:
    - delegated
