---
- name: Configure solr node as slave
  blockinfile:
    dest: '{{ solr_configset_path }}/{{ item.item | basename }}/conf/solrconfig.xml'
    insertafter: '.*<requestHandler name="/replication" class="solr.ReplicationHandler".*>'
    marker: ' <!-- {mark} solr ansible custom block --> '
    block: |
      <lst name="slave">
      <str name="masterUrl">{{ solr_master_generated_url }}</str>
      <str name="pollInterval">00:00:60</str>
      </lst>
    state: present
  become: True
  loop: '{{ true_configset_xml_list.results }}'
  when: item.matched
  notify:
    - restart Solr Linux
