---
- name: Configure solr node as master
  blockinfile:
    dest: '{{ solr_configset_path }}/{{ item.item | basename }}/conf/solrconfig.xml'
    insertafter: '.*<requestHandler name="/replication" class="solr.ReplicationHandler".*>'
    marker: ' <!-- {mark} solr ansible custom block --> '
    block: |
      <lst name="master">
      <str name="replicateAfter">commit</str>
      <str name="replicateAfter">startup</str>
      <str name="confFiles">schema.xml,stopwords.txt</str>
      </lst>
    state: present
  become: True
  loop: '{{ true_configset_xml_list.results }}'
  when: item.matched
  notify:
    - restart Solr Linux
