---
- name: Configure solr node as master
  win_lineinfile:
    path: '{{ solr_configset_path }}/{{ item.item | win_basename }}\conf\solrconfig.xml'
    insertafter: '.*<requestHandler name="/replication" class="solr.ReplicationHandler".*>'
    line:
      '<!-- BEGIN solr ansible custom block --> <lst name="master">
      <str name="replicateAfter">commit</str>
      <str name="replicateAfter">startup</str>
      <str name="confFiles">schema.xml,stopwords.txt</str> </lst>
      <!-- END solr ansible custom block -->'
    regexp:
      '<!--\sBEGIN\ssolr\sansible\scustom\sblock(.*)
      END\ssolr\sansible\scustom\sblock\s-->'
  when: item.stdout_lines | length
  loop: '{{ true_configset_xml_list.results }}'
  notify:
    - restart Solr Windows
