---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-Windows2016-solr-slave-solr7
    image_id: ami-00a20f508263efd30
    platform: windows2016core
    region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: True
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - slave

  - name: test-aws-Windows2016-solr_master-solr8
    image_id: ami-00a20f508263efd30
    platform: windows2016core
    region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: True
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr8

  - name: test-aws-Windows2019-solr_master-solr7
    image_id: ami-0477b9335a5a75438
    platform: windows2019core
    region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: True
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - solr_master

  - name: test-aws-Windows2019-solr-slave-solr8
    image_id: ami-0477b9335a5a75438
    platform: windows2019core
    region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-314c223d
    assign_public_ip: True
    spot_price: 0.14
    security_group_name:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr8
      - slave

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      all:
        ansible_connection: winrm
        solr_patch_transport_web: '{{ lookup("env","STORAGE_AWS") }}/hybris-solr'
      solr7:
        solr_version: 7.7.1
      solr8:
        solr_version: 8.0.0
      slave:
        solr_instance_type: slave
        solr_master_defined_host: solr_master.example.com
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        ansible_connection: winrm
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
