---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-Windows2016-solr-slave-solr7
    aws_image_id: ami-07a29e78aeb420471
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-01be2149
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - slave

  - name: test-aws-Windows2016-solr-master-solr8
    aws_image_id: ami-07a29e78aeb420471
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-01be2149
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr8

  - name: test-aws-Windows2019-solr-master-solr7
    aws_image_id: ami-03ad37b4adab50a4c
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-01be2149
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - solr-master

  - name: test-aws-Windows2019-solr-slave-solr8
    aws_image_id: ami-03ad37b4adab50a4c
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-01be2149
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
    wait_timeout: 1800
    groups:
      - windows
      - solr8
      - slave

provisioner:
  name: ansible
  log: False
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      all:
        solr_patch_transport_web: '{{ lookup("env","STORAGE_AWS") }}/hybris-solr'
      solr7:
        solr_version: 7.7.1
      solr8:
        solr_version: 8.0.0
      slave:
        solr_instance_type: slave
        solr_master_defined_host: solr-master.example.com
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', True) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
  playbooks:
    create: ../resources/provisioning/WINRM/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
