---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-Windows2016-solr-slave-solr7
    aws_image_id: ami-00a20f508263efd30
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
      - molecule
    wait_timeout: 1800
    groups:
      - windows
      - solr7
      - slave

  - name: test-aws-Windows2016-solr-master-solr8
    aws_image_id: ami-00a20f508263efd30
    aws_region: us-east-1
    instance_type: m5.large
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: True
    spot_price: 0.14
    aws_sec_group:
      - default
      - molecule
    wait_timeout: 1800
    groups:
      - windows
      - solr8

provisioner:
  name: ansible
  log: True
  connection_options:
    ansible_connection: winrm
  inventory:
    group_vars:
      solr7:
        solr_version: 7.7.1
      solr8:
        solr_version: 8.0.0
      slave:
        solr_instance_type: slave
        solr_master_defined_host: solr-master.example.com
      windows:
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', True) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
  playbooks:
    create: create.yml
    #create: ../resources/provisioning/WINRM/create.yml
    destroy: ../resources/provisioning/WINRM/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
