---
- name: Converge
  hosts: all
  tasks:
    - name: Perform a GET and Store Output
      win_uri:
        url: https://api.ipify.org?format=json
        return_content: True
      register: http_output

    - name: Out public ip
      debug:
        var: http_output

  # roles:
  #   - role: lean_delivery.java
  #   - role: lean_delivery.solr_standalone
  #   - role: ansible-role-solr-cluster
  vars:
    solr_change_default_password: False
    solr_copy_default_configsets: True
    solr_use_java_version_8: False
