---
- name: Install java and solr-standalone
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
  vars:
    solr_change_default_password: False
    solr_copy_default_configsets: True
    solr_use_java_version_8: False
