---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: web
      transport_web: "{{ lookup('env','STORAGE_AWS') }}/oracle-java/jdk-8u45-windows-x64.exe"
      java_major_version: 8
      java_minor_version: 45
    - role: lean_delivery.solr_standalone
    - role: ansible-role-solr-cluster
  vars:
    solr_change_default_password: False
    solr_copy_default_configsets: True
