---
- name: Prepare Ubuntu / Debian
  hosts: debian_family
  gather_facts: False
  tasks:

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt install -y python-minimal)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

- name: Prepare RHEL
  hosts: rhel_family
  gather_facts: False
  tasks:

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

- name: Install java and solr-standalone
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
  vars:
    solr_change_default_password: False
    solr_copy_default_configsets: True
    solr_use_java_version_8: False
