---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-solr-slave
    image: leandelivery/docker-systemd:centos7
    privileged: True
    groups:
      - rhel_family
      - slave

  - name: test-docker-ubuntu1804-solr-slave
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: True
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - slave

provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        solr_patch_transport_web: '{{ lookup("env","STORAGE_AWS") }}/hybris-solr'
      slave:
        solr_instance_type: slave
        solr_master_defined_host: solr-master.example.com
  playbooks:
    prepare: ../resources/prepare.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
