---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-epc-centos7-solr-slave
    image: CentOS7_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - rhel_family
      - slave

  - name: test-epc-ubuntu1804-solr_master
    image: Ubuntu18.04_64-bit
    shape: small
    region: EPAM-BY2
    wait_timeout: 3600
    groups:
      - debian_family
      - solr_master

provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        solr_patch_transport_web: '{{ lookup("env","STORAGE_EPC") }}/hybris-solr'
        solr_version: 8.0.0
      slave:
        solr_instance_type: slave
        solr_master_defined_host: solr_master.example.com
  playbooks:
    create: ../resources/provisioning/EPC/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/EPC/destroy.yml
    verify: ../resources/tests/verify.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-epc-delegated
verifier:
  name: ansible
  lint:
    name: ansible-lint
